create table if not exists public.laptops (
  id bigint generated by default as identity primary key,
  name text not null,
  brand text not null,
  category text not null default 'Gaming',
  price numeric not null check (price >= 0),
  cpu text not null default '',
  gpu text not null default '',
  ram text not null default '',
  storage text not null default '',
  display text not null default '',
  os text not null default '',
  keyboard text not null default '',
  image text not null default '/images/placeholder.jpg',
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id text not null,
  customer_name text not null,
  customer_email text not null,
  customer_phone text not null,
  shipping_address jsonb not null,
  payment_method text,
  items jsonb not null,
  total_amount numeric not null check (total_amount >= 0),
  status text not null default 'completed',
  created_at timestamptz not null default now()
);

create index if not exists orders_customer_email_created_at_idx
  on public.orders (customer_email, created_at desc);

alter table public.laptops enable row level security;
alter table public.orders enable row level security;

create policy "Anyone can view laptops"
  on public.laptops for select using (true);

notify pgrst, 'reload schema';
